<?php
session_start();

// Ensure the user is logged in before accessing the page
if (!isset($_SESSION['user_id'])) {
    header('Location: index.php');
    exit;
}


require_once('tcpdf/tcpdf.php');


// Database connection details
$servername = "localhost"; 
$username = "root"; 
$password = ""; 
$database = "project2"; 

// Create connection
$conn = new mysqli($servername, $username, $password, $database);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Assuming the user is already authenticated and their ID is stored in a session
$userId = $_SESSION['user_id'];

// Fetch username
$userQuery = "SELECT Name FROM users WHERE UserID = '$userId'";
$userResult = $conn->query($userQuery);
$username = ($userResult->num_rows > 0) ? $userResult->fetch_assoc()['Name'] : 'Guest';

// Fetch reports for the logged-in user
$reportsQuery = "SELECT works, uploaded_at FROM reports WHERE UserID = '$userId' ORDER BY uploaded_at DESC";
$reportsResult = $conn->query($reportsQuery);

if ($reportsResult->num_rows > 0) {
    // Initialize HTML content for the final report
    $htmlContent = '<h1 style="text-align:center;">Final Report</h1>';
    $htmlContent .= '<h2 style="text-align:center;">Submitted by: ' . htmlspecialchars($username) . '</h2>';
    $htmlContent .= '<hr>';

    // Concatenate all reports
    while($reportRow = $reportsResult->fetch_assoc()) {
        $htmlContent .= '<h3>Report Date: ' . htmlspecialchars($reportRow['uploaded_at']) . '</h3>';
        $htmlContent .= '<p>' . nl2br(htmlspecialchars($reportRow['works'])) . '</p>';
        $htmlContent .= '<hr>';
    }

    // Include TCPDF library
    require_once('tcpdf/tcpdf.php');

    // Create new PDF document
    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

    // Set document information
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Student Dashboard');
    $pdf->SetTitle('Final Report');
    $pdf->SetSubject('Generated Report');
    $pdf->SetKeywords('TCPDF, PDF, report, student');

    // Set default header data
    $pdf->SetHeaderData('', 0, 'Final Report', 'Generated by Student Dashboard', array(0,64,255), array(0,64,128));
    $pdf->setFooterData(array(0,64,0), array(0,64,128));

    // Set header and footer fonts
    $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

    // Set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

    // Set margins
    $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

    // Set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

    // Set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

    // Add a page
    $pdf->AddPage();

    // Output the HTML content
    $pdf->writeHTML($htmlContent, true, false, true, false, '');

    // Close and output PDF document
    $pdf->Output('final_report_' . $userId . '.pdf', 'D');
} else {
    echo "No reports submitted.";
}

$conn->close();
?>
